In [2]:
import torch

In [3]:
a = torch.randint(low=0, high=5, size=(5,))
b = torch.tensor([1,3])

In [5]:
b.outer(a)

tensor([[ 4,  0,  3,  3,  2],
        [12,  0,  9,  9,  6]])

In [7]:
i = torch.arange(0, 64 , 2) # the -2 part will be already dene when taken the arange with step of 2
print(i)

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
        36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62])


In [8]:
theta = 1 / ( 10000 ** (i / 64))
theta

tensor([1.0000e+00, 7.4989e-01, 5.6234e-01, 4.2170e-01, 3.1623e-01, 2.3714e-01,
        1.7783e-01, 1.3335e-01, 1.0000e-01, 7.4989e-02, 5.6234e-02, 4.2170e-02,
        3.1623e-02, 2.3714e-02, 1.7783e-02, 1.3335e-02, 1.0000e-02, 7.4989e-03,
        5.6234e-03, 4.2170e-03, 3.1623e-03, 2.3714e-03, 1.7783e-03, 1.3335e-03,
        1.0000e-03, 7.4989e-04, 5.6234e-04, 4.2170e-04, 3.1623e-04, 2.3714e-04,
        1.7783e-04, 1.3335e-04])

In [10]:

m = torch.arange(0, 11)
m

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:

freq = torch.outer(m, theta).float()

In [12]:
freq

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00],
        [1.0000e+00, 7.4989e-01, 5.6234e-01, 4.2170e-01, 3.1623e-01, 2.3714e-01,
         1.7783e-01, 1.3335e-01, 1.0000e-01, 7.4989e-02, 5.6234e-02, 4.2170e-02,
         3.1623e-02, 2.3714e-02, 1.7783e-02, 1.3335e-02, 1.0000e-02, 7.4989e-03,
         5.6234e-03, 4.2170e-03, 3.1623e-03, 2.3714e-03, 1.7783e-03, 1.3335e-03,
         1.0000e-03, 7.4989e-04, 5.6234e-04, 4.2170e-04, 3.1623e-04, 2.3714e-04,
         1.7783e-04, 1.3335e-04],
        [2.0000e+00, 1.4998e+00, 1.1247e+00, 8.4339e-01, 6.3246e-01, 4.7427e-01,
         3.5566e-01, 2.6670e-01, 2.0000e-

In [13]:



precomputed = torch.polar(torch.ones_like(freq), freq)

In [65]:
embedding = torch.tensor([[[[1,2,3,4]]]]).float()

In [66]:
embedding.shape

torch.Size([1, 1, 1, 4])

In [67]:
torch.view_as_complex(embedding.reshape(*embedding.shape[:-1],-1,2))

tensor([[[[1.+2.j, 3.+4.j]]]])

In [73]:
embedding = torch.tensor([[[[1,2,3,4],[6,7,8,9]]],[[[1,2,3,4],[6,7,8,9]]]]).float()
embedding.size()

torch.Size([2, 1, 2, 4])

In [74]:
embedding

tensor([[[[1., 2., 3., 4.],
          [6., 7., 8., 9.]]],


        [[[1., 2., 3., 4.],
          [6., 7., 8., 9.]]]])

In [75]:
torch.view_as_complex(embedding.reshape(*embedding.shape[:-1],-1,2))


tensor([[[[1.+2.j, 3.+4.j],
          [6.+7.j, 8.+9.j]]],


        [[[1.+2.j, 3.+4.j],
          [6.+7.j, 8.+9.j]]]])