In [1]:
from pathlib import Path
import torch

In [3]:
p = Path('text.ipynb')/ 'hai'

In [10]:
tt = torch.cat((torch.Tensor([20]*10),torch.tensor([10,10]))) == 10.

In [13]:
torch.where(tt, 10, 0)

tensor([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 10, 10])

In [29]:
tem = torch.randint(1,20, size=(5,3))

In [33]:
tem[0:,:2]=0

In [36]:
tem = tem==0

In [41]:
tem[:,0]

tensor([True, True, True, True, True])

In [39]:
te = torch.rand(size=(5,3))

In [40]:
te

tensor([[0.2236, 0.8560, 0.2038],
        [0.9931, 0.1277, 0.7536],
        [0.0701, 0.6389, 0.4718],
        [0.6245, 0.3988, 0.9802],
        [0.2344, 0.7095, 0.4998]])

In [42]:
torch.where(tem[:,0],te[:,0], 2)

tensor([0.2236, 0.9931, 0.0701, 0.6245, 0.2344])

In [49]:
tem

tensor([[ True,  True, False],
        [ True,  True, False],
        [ True,  True, False],
        [ True,  True, False],
        [ True,  True, False]])

In [55]:
torch.where(tem[:,2],te[:,0], torch.tensor([1,2,35,4,5]))

tensor([ 1.,  2., 35.,  4.,  5.])

In [52]:
te[:,1] = torch.where(tem[:,0],te[:,0], 2)

In [45]:
te

tensor([[0.2236, 0.2236, 0.2038],
        [0.9931, 0.9931, 0.7536],
        [0.0701, 0.0701, 0.4718],
        [0.6245, 0.6245, 0.9802],
        [0.2344, 0.2344, 0.4998]])

In [18]:
torch.tensor([False]*19)

tensor([False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False])

In [2]:
torch.cuda.is_available()

True